name: livetrack24-location-retrieval

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-livetrack24:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run livetrack24 retrieval script
        run: python sources/livetrack24-location-retrieval.py

      - name: Commit and push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/livetrack24-location-data.json
          git diff --cached --quiet || git commit -m "Update LiveTrack24 location"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}