name: live-location-retrievals

on:
  schedule:
    - cron: "*/4 * * * *"
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed
permissions:
  contents: write

jobs:
  update-live-location-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4

      - name: Run livetrack24 retrieval script
        run: python sources/livetrack24-location-retrieval.py

      - name: Run skylines retrieval script
        run: python sources/skylines-location-retrieval.py

      - name: List public/data contents
        run: ls -al public/data

      # - name: Show file contents
      #   run: cat public/data/livetrack24-location-data.json

      - name: Commit and push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase
          git add public/data/.
          git status
          git diff --cached --quiet || git commit -m "Update live tracking Locations"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}