name: live-location-retrievals

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed
permissions:
  contents: write

jobs:
  update-live-location-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run retrieval script
        run: python sources/locationRetrieval.py
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: List public/data contents
        run: ls -al public/data

      - name: Show file contents
        run: cat public/data/location-data.json

      - name: Add deploy timestamp to force cache invalidation
        run: |
          echo "Updated at $(date -u)" > public/last-updated.txt

      - name: Commit and push updated data to gh-pages
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

          git fetch origin gh-pages
          git worktree add gh-pages-worktree gh-pages
          mkdir -p gh-pages-worktree/public/data
          cp public/data/location-data.json gh-pages-worktree/public/data/location-data.json
          cp public/last-updated.json gh-pages-worktree/public/last-updated.json

          cd gh-pages-worktree
          git add public/data/location-data.json public/last-updated.txt
          git commit -m "Update location data and trigger pages to rebuild [bot]" || echo "No changes"
          git push origin gh-pages || git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Commit and push updated data to gh-pages
      #   run: |
      #     cp public/data/location-data.json /tmp/location-data.json

      #     git fetch origin gh-pages
      #     git switch gh-pages || git checkout -b gh-pages
      #     git reset --hard origin/gh-pages
      #     git branch --show-current 

      #     rm -rf public
      #     mkdir -p public/data
      #     cp /tmp/location-data.json public/data/location-data.json
      #     echo "Updated at $(date -u)" > public/last-updated.txt
      #     touch public/.nojekyll

      #     git config user.name github-actions[bot]
      #     git config user.email github-actions[bot]@users.noreply.github.com
      #     git add public/data/location-data.json
      #     git commit -m "Update location data [bot]" || echo "No changes"
      #     git push origin gh-pages || git push origin gh-pages --force
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List public/data contents
        run: ls -al public/data

      - name: Curl live file from github Pages
        run: |
          sleep 10
          curl -sL "https://traviskool.github.io/offgrid-tracking/data/location-data.json?ts=$(date +%s)"